import sgMail from "@sendgrid/mail";
import type { Summary, User } from "@shared/schema";
import { generateDOCX, generatePDF } from "./exportService";

if (!process.env.SENDGRID_API_KEY) {
  throw new Error("SENDGRID_API_KEY environment variable must be set");
}

sgMail.setApiKey(process.env.SENDGRID_API_KEY!);

export async function sendSummaryEmail(
  summary: Summary,
  recipients: string[],
  subject: string,
  format: "html" | "pdf" | "both",
  sender: User,
  ccSelf?: boolean
): Promise<void> {
  try {
    const attachments: any[] = [];

    // Generate attachments based on format
    if (format === "pdf" || format === "both") {
      const pdfBuffer = await generatePDF(summary);
      attachments.push({
        content: pdfBuffer.toString("base64"),
        filename: `${summary.title}.pdf`,
        type: "application/pdf",
        disposition: "attachment",
      });
    }

    if (format === "both") {
      const docxBuffer = await generateDOCX(summary);
      attachments.push({
        content: docxBuffer.toString("base64"),
        filename: `${summary.title}.docx`,
        type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        disposition: "attachment",
      });
    }

    // Prepare email content
    const htmlContent =
      format === "html" || format === "both"
        ? `
        <html>
          <body style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
            <h1 style="color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
              ${summary.title}
            </h1>
            <div style="background-color: #f9fafb; padding: 15px; border-radius: 8px; margin: 20px 0;">
              <strong>Generated by:</strong> ${sender.fullName} (${
            sender.email
          })<br>
              <strong>Date:</strong> ${new Date(
                summary.createdAt!
              ).toLocaleDateString()}<br>
              <strong>Word Count:</strong> ${summary.wordCount} words
            </div>
            <div style="line-height: 1.6; white-space: pre-wrap;">
              ${summary.summaryContent.replace(/\n/g, "<br>")}
            </div>
            <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;">
            <p style="color: #6b7280; font-size: 14px;">
              This summary was generated using SummaryFlow - AI Meeting Transcript Summarization
            </p>
          </body>
        </html>
      `
        : undefined;

    const textContent = `
${summary.title}

Generated by: ${sender.fullName} (${sender.email})
Date: ${new Date(summary.createdAt!).toLocaleDateString()}
Word Count: ${summary.wordCount} words

${summary.summaryContent}

---
This summary was generated using SummaryFlow - AI Meeting Transcript Summarization
    `;

    const mailOptions = {
      to: recipients,
      from: {
        email: sender.email,
        name: sender.fullName,
      },
      cc: ccSelf ? [sender.email] : undefined,
      subject: subject,
      text: textContent,
      html: htmlContent,
      attachments: attachments,
    };

    await sgMail.send(mailOptions);
  } catch (error: any) {
    throw new Error(`Email sending failed: ${error.message}`);
  }
}
